const tasks = {
  "task-1": {
    title: "Implement Login Page",
    description: "Design and code the login page for Join.",
    dueDate: "2025-04-01",
    priority: "urgent",
    assigned: ["AW", "TW"],
    subtasks: ["Design UI", "Code Frontend", "Test Functionality"],
    completedSubtasks: 2,
    status: "todo",
    category: "User Story",
  },
  "task-2": {
    title: "Fix API Integration",
    description: "Resolve issues with the API for task creation.",
    dueDate: "2025-04-05",
    priority: "medium",
    assigned: ["TW", "DF"],
    subtasks: ["Debug API", "Update Endpoints", "Test Integration"],
    completedSubtasks: 1,
    status: "in-progress",
    category: "Technical Task",
  },
  "task-3": {
    title: "Design Homepage",
    description: "Create the homepage layout for Join.",
    dueDate: "2025-03-30",
    priority: "low",
    assigned: ["DF"],
    subtasks: ["Create Wireframe", "Design UI", "Get Feedback"],
    completedSubtasks: 3,
    status: "done",
    category: "User Story",
  },
  "task-4": {
    title: "Optimize Database",
    description: "Improve the performance of the database queries.",
    dueDate: "2025-04-10",
    priority: "medium",
    assigned: ["DF", "AW"],
    subtasks: [
      "Analyze Queries",
      "Optimize Indexes",
      "Test Performance",
      "Deploy Changes",
    ],
    completedSubtasks: 0,
    status: "todo",
    category: "Technical Task",
  },
  "task-5": {
    title: "Add User Authentication",
    description: "Implement user authentication for Join.",
    dueDate: "2025-04-15",
    priority: "urgent",
    assigned: ["TW", "DF", "AW"],
    subtasks: [
      "Set Up Auth Server",
      "Implement Login",
      "Implement Logout",
      "Test Security",
      "Deploy",
    ],
    completedSubtasks: 1,
    status: "todo",
    category: "User Story",
  },
};
